import com.grosner.multiplatformexample.LocalizableString

//Autogenerated File
enum class StringPath(override val key: String) : LocalizableString {
    Loading_Header("loading.header"),
    Loading_Message("loading.message"),
    Loading_Success_message("loading.success_message"),
    Loading_Success_title("loading.success_title"),
    Login_Body("login.body"),
    Login_Header("login.header"),
    Login_Primary_cta("login.primary_cta"),
    Login_Secondary_cta("login.secondary_cta"),
    Profile_Edit_cta("profile.edit_cta"),
    Profile_Header("profile.header"),
    Profile_Message("profile.message"),
    Profile_Settings_cta("profile.settings_cta");
}
